### ISSUE TITLE
PRS tools

### ISSUE THREAD

**Issue by joellepasman** [comorment/containers#17]
Could you make sure the following packages are  available and fully functional:
- LDpred2: https://privefl.github.io/bigsnpr/articles/LDpred2.html (not sure if you have LDpred or LDpred2, also it may need a usecase)
- PRSice2 (I think this one is covered as it's included in a usecase)
- GCTA-SBLUP (it is installed but it may need some testing + a usecase)

**Comment by bayramakdeniz** [comment]
@ttfiliz  could you run LDpred with our demo summary statistic data that has already been used to run with PRSICE2. We already have LDpred in python3.sif container hence you do not need to add it. The first thing you may do is to run LDpred to get polygenic risk scores using the demo data (that had been used for PRSICE2).  You may find some info about how to run LDpred here  https://www.intro-statistical-genetics.com/data-code (chapter 10)

There are also test data examples on their website: https://github.com/bvilhjal/ldpred

Afterwards we may integrate it into gwas.py but as a first attempt lets do it without gwas.py

**Comment by deepchocolate** [comment]
I had problems getting LDPred to work, due to some bug in LDPred. Don't know if it was something specif to the data I used, but others have had the same bug. In the end I just gave up and went for LDPred2. If want to get it into gwas.py I can make a PR for it.

**Comment by bayramakdeniz** [comment]
Thanks Andreas, If you can do it would be great @deepchocolate . @ttfiliz then you can suspend to focus on LDpred for a while. Alternatively, can you have a look at how to run GCTA-SBLUP for PRS calculation while Andreas is working on LDPred2

**Comment by espenhgn** [comment]
Hi. Fyi, LDpred2 is included in some R-based builds in preparation at https://github.com/espenhgn/ldpred2

**Comment by deepchocolate** [comment]
@ofrei @bayramakdeniz 
I've placed some suggestions of an implementation of LDPred2 in branch `deepchocolate/ldpred2`
https://github.com/comorment/containers/compare/deepchocolate/ldpred2?expand=1

I don't know enough about the set-up in this repo so I've just placed everything I used in tests/ldpred2 for now.
Basically I've used the LDPred2 tutorial to make an R-script. See `tests/ldpred2/run_ldpred2.sh`

I used my own container for this purpose and since it's not created in the same way as you do it I have not made any modifications in existing scripts.

I used some available sample data in the repo to test and had to to some "phony" imputation for that purpose

**Comment by espenhgn** [comment]
To summarize a bit:

| method | software | container |
| -------- | --------- | --------- |
| ldpred   | ldpred (py)    | python3 .sif |
l ldpred2 | bigsnpr (R)  | - |
| PRSice | PRSice (bin) | gwas.sif |
| SBayesR/S | gctb | gwas.sif |
| GCTA-SBLUP | gcta | gwas.sif/r.sif |
| PRS-CS | PRScs (py) | - |
| MegaPRS | LDAK (bin) | - |

**Comment by espenhgn** [comment]
As you may have received a notification, merging #107 closed this ticket but LDAK/MegaPRS and PRScs might still be useful additions. LDAK installation was at some point part of #107, may cherry pick these in a separate PR. PRScs has been requested for some PGS related project.
