### ISSUE TITLE
Regenie throws error for step1 if there are more than 1M variants

### ISSUE THREAD

**Issue by bayramakdeniz** [comorment/containers#237]
Using opensnp data with REGENIE, I faced the following error 

<img width="1149" alt="Screenshot 2024-03-06 at 15 59 09" src="https://github.com/comorment/containers/assets/66322504/91bca195-b8ee-4a7e-b2c0-0595507826c5">

We may either add --force-step1 option to gwas.py as suggested or make sure that the input size will be lower than 1M (such as unimputed version of the data as suggested in the Regenie webpage)

**Comment by espenhgn** [comment]
Hi @bayramakdeniz. Can you provide a fix in a PR?

**Comment by ofrei** [comment]
@bayramakdeniz good catch. I thought running regenie on 1.2M SNPs (HapMap3 set) would be quite reasonable. I guess the intention of this check was to make sure people don't run regenie on ~10 million SNPs or so, but whether its 1 million or 1.2 million shouldn't matter.

I think we can fix it either way: ok to use  a subset of SNPs from opensnp (this shoudl be ok, especially in tutorial), but also OK to pass on ``--force-step1``. I assume regenie takes quite a while to run, so for a purpose of this example I would reduce the number of SNPs, for example using "--maf 0.05" followed by LD prunning (LD r2 0.9) - with a very liberal threshold of 0.9 because I don't think SNPs passed on to regenie are expected to be LD-independent.

**Comment by ofrei** [comment]
All in all I think ``--force-step1`` is the best option here, for now. 

Later I can add --extract option to gwas.py, and pass it along to regenie's  --extract option for selecting a subset of SNPs; then  we can have a file in opensnp dataset listing rs# after filtering as I described (--maf 0.05" followed by LD prunning (LD r2 0.9) ).

**Comment by bayramakdeniz** [comment]
Is the --force-step1 option also available?

**Comment by ttfiliz** [comment]
It's not available yet, but I'll try to implement that as well.
