### ISSUE TITLE
Dockerfile recipes: is `libquadmath0` essential?  

### ISSUE THREAD

**Issue by espenhgn** [comorment/containers#46]
This Debian package which is not (yet) supporting all architectures (e.g., arm64) is installed via https://github.com/comorment/gwas/blob/e3f295087b11866d12d3da9d5ba5c5d929e7272a/scripts/apt_get_essential.sh across different containers. What tools except `Linux-king` (https://github.com/comorment/gwas/blob/b6209ffbad73e4f638e9057b1f2612a3d0e0a625/scripts/install_king.sh) require this library?

**Comment by ofrei** [comment]
I don't really know. It's fine to drop libquadmath0 and see what happens.
Here is a reference to ``king`` software:  https://www.kingrelatedness.com/Download.shtml , which has instructions how to build this software and link to downloadable pre-built binaries. 
Checking source code, I can't really see that ``king`` uses quadmath - so perhaps even King works with without this lib.

**Comment by ofrei** [comment]
But KING software is indeed useful, it's good to include it in our container. At some point we had to make a minor fix in that tool :
https://github.com/norment/moba_qc_imputation/commit/e661296cdeebdca627045c83eb6e5770ee20ba47
It would be good to bring this up with KING software maintainers to see if they can include this . The issue was that KING generated 500 GB+ large text files as output, most of that output was completely irrelevant. The patch was to filter on some reasonable threshold of relatedness (we hardcoded it as 0.025) - then the file was reduced down to a few megabytes in size.

**Comment by espenhgn** [comment]
I'll deal with this issue in a separate PR.

**Comment by espenhgn** [comment]
@ofrei , regarding the KING software: Perhaps the developers could be persuaded somehow to move this project to git (and github, gitlab, or equivalent) somehow, as this software appears to be updated regularly still. Right now we just grab their prebuilt binary without compiling it. I suppose we could build it ourselves and apply patches during the build.
