### ISSUE TITLE
Software: SHAPEIT.v2 to SHAPEIT4?

### ISSUE THREAD

**Issue by espenhgn** [comorment/containers#50]
Hi @ofrei; The `gwas` dockerfile at https://github.com/comorment/gwas incorporates binaries of an older version of this software from https://mathgen.stats.ox.ac.uk/genetics_software/shapeit/shapeit.html. 
There's a more recent version with sources and MIT license available from https://github.com/odelaneau/shapeit4.
Should we rather package that?

**Comment by ofrei** [comment]
In MoBa QC & Imputation we deliberately use SHAPEIT2 because of it's ``--duoHMM`` option for handling complex family structure, which had been removed in SHAPEIT4. SHAPEIT4 has other advantages over SHAPEIT2 which may outweight lack of ``--duoHMM`` option, and we're going to evaluate this in more detail as part of MoBa imputation, but generally the point is that upgrading in this case is not a straightforward win-win.
However I agree that due to SHAPEIT2 license we need to either remove it from containers, or ask for permission from software owners. Let's keep this ticket opened until this is addressed.

**Comment by espenhgn** [comment]
The (academic) [LICENSE](https://mathgen.stats.ox.ac.uk/genetics_software/shapeit/shapeit.html) clearly states "The SHAPEIT software remains at your Institution and is not published, distributed, or otherwise transferred or made available to other than Institution employees and students involved in research under your supervision. If you wish to obtain SHAPEIT for any commercial purposes or for diffusion through the internet, you will need to execute a separate licensing agreement with CNAM and pay a fee."

**Comment by espenhgn** [comment]
We will include Shapeit4 in future builds.
